# Generated by Django 3.1.7 on 2021-03-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('NATURE', 'nature'), ('FESTIVALS', 'festivals'), ('TRAVEL', 'travel'), ('CELEBRATION', 'celebration')], max_length=50)),
            ],
        ),
    ]
